package pine.html;

#if (js && !nodejs)
typedef Event = js.html.Event;
#else
typedef Event = Dynamic;
#end
typedef EventListener = (e:Event) -> Void;

// From https://github.com/haxetink/tink_domspec/blob/master/src/tink/domspec/Events.hx
typedef HtmlEvents = {
  @:attr('onwheel') final ?onWheel:EventListener;
  @:attr('oncopy') final ?onCopy:EventListener;
  @:attr('oncut') final ?onCut:EventListener;
  @:attr('onpaste') final ?onPaste:EventListener;
  @:attr('onabort') final ?onAbort:EventListener;
  @:attr('onblur') final ?onBlur:EventListener;
  @:attr('onfocus') final ?onFocus:EventListener;
  @:attr('oncanplay') final ?onCanPlay:EventListener;
  @:attr('oncanplaythrough') final ?onCanPlayThrough:EventListener;
  @:attr('onchange') final ?onChange:EventListener;
  @:attr('onclick') final ?onClick:EventListener;
  @:attr('oncontextmenu') final ?onContextMenu:EventListener;
  @:attr('ondblclick') final ?onDblClick:EventListener;
  @:attr('ondrag') final ?onDrag:EventListener;
  @:attr('ondragend') final ?onDragEnd:EventListener;
  @:attr('ondragenter') final ?onDragEnter:EventListener;
  @:attr('ondragleave') final ?onDragLeave:EventListener;
  @:attr('ondragover') final ?onDragOver:EventListener;
  @:attr('ondragstart') final ?onDragStart:EventListener;
  @:attr('ondrop') final ?onDrop:EventListener;
  @:attr('ondurationchange') final ?onDurationChange:EventListener;
  @:attr('onemptied') final ?onEmptied:EventListener;
  @:attr('onended') final ?onEnded:EventListener;
  @:attr('oninput') final ?onInput:EventListener;
  @:attr('oninvalid') final ?onInvalid:EventListener;
  @:attr('oncompositionstart') final ?onCompositionStart:EventListener;
  @:attr('oncompositionupdate') final ?onCompositionUpdate:EventListener;
  @:attr('oncompositionend') final ?onCompositionEnd:EventListener;
  @:attr('onkeydown') final ?onKeyDown:EventListener;
  @:attr('onkeypress') final ?onKeyPress:EventListener;
  @:attr('onkeyup') final ?onKeyUp:EventListener;
  @:attr('onload') final ?onLoad:EventListener;
  @:attr('onloadeddata') final ?onLoadedData:EventListener;
  @:attr('onloadedmetadata') final ?onLoadedMetadata:EventListener;
  @:attr('onloadstart') final ?onLoadStart:EventListener;
  @:attr('onmousedown') final ?onMouseDown:EventListener;
  @:attr('onmouseenter') final ?onMouseEnter:EventListener;
  @:attr('onmouseleave') final ?onMouseLeave:EventListener;
  @:attr('onmousemove') final ?onMouseMove:EventListener;
  @:attr('onmouseout') final ?onMouseOut:EventListener;
  @:attr('onmouseover') final ?onMouseover:EventListener;
  @:attr('onmouseup') final ?onMouseUp:EventListener;
  @:attr('onpause') final ?onPause:EventListener;
  @:attr('onplay') final ?onPlay:EventListener;
  @:attr('onplaying') final ?onPlaying:EventListener;
  @:attr('onprogress') final ?onProgress:EventListener;
  @:attr('onratechange') final ?onRateChange:EventListener;
  @:attr('onreset') final ?onReset:EventListener;
  @:attr('onresize') final ?onResize:EventListener;
  @:attr('onscroll') final ?onScroll:EventListener;
  @:attr('onseeked') final ?onSeeked:EventListener;
  @:attr('onseeking') final ?onSeeking:EventListener;
  @:attr('onselect') final ?onSelect:EventListener;
  @:attr('onshow') final ?onShow:EventListener;
  @:attr('onstalled') final ?onStalled:EventListener;
  @:attr('onsubmit') final ?onSubmit:EventListener;
  @:attr('onsuspend') final ?onSuspend:EventListener;
  @:attr('ontimeupdate') final ?onTimeEpdate:EventListener;
  @:attr('onvolumechange') final ?onVolumeChange:EventListener;
  @:attr('onwaiting') final ?onWaiting:EventListener;
  @:attr('onpointercancel') final ?onPointerCancel:EventListener;
  @:attr('onpointerdown') final ?onPointerDown:EventListener;
  @:attr('onpointerup') final ?onPointerUp:EventListener;
  @:attr('onpointermove') final ?onPointerMove:EventListener;
  @:attr('onpointerout') final ?onPointerOut:EventListener;
  @:attr('onpointerover') final ?onPointerOver:EventListener;
  @:attr('onpointerenter') final ?onPointerEnter:EventListener;
  @:attr('onpointerleave') final ?onPointerLeave:EventListener;
  @:attr('ongotpointercapture') final ?onGotPointerCapture:EventListener;
  @:attr('onlostpointercapture') final ?onLostPointerCapture:EventListener;
  @:attr('onfullscreenchange') final ?onFullScreenChange:EventListener;
  @:attr('onfullscreenerror') final ?onFullScreenError:EventListener;
  @:attr('onpointerlockchange') final ?onPointerLockChange:EventListener;
  @:attr('onpointerlockerror') final ?onPointerLockError:EventListener;
  @:attr('onerror') final ?onError:EventListener;
  @:attr('ontouchstart') final ?onTouchStart:EventListener;
  @:attr('ontouchend') final ?onTouchEnd:EventListener;
  @:attr('ontouchmove') final ?onTouchMove:EventListener;
  @:attr('ontouchcancel') final ?onTouchCancel:EventListener;
}
