package pine2.html;

#if (js && !nodejs)
typedef Event = js.html.Event;
#else
typedef Event = Dynamic;
#end
typedef EventListener = (e:Event) -> Void;

// From https://github.com/haxetink/tink_domspec/blob/master/src/tink/domspec/Events.hx
typedef HtmlEvents = {
  @:optional final onwheel:HtmlAttribute<EventListener>;
  @:optional final oncopy:HtmlAttribute<EventListener>;
  @:optional final oncut:HtmlAttribute<EventListener>;
  @:optional final onpaste:HtmlAttribute<EventListener>;
  @:optional final onabort:HtmlAttribute<EventListener>;
  @:optional final onblur:HtmlAttribute<EventListener>;
  @:optional final onfocus:HtmlAttribute<EventListener>;
  @:optional final oncanplay:HtmlAttribute<EventListener>;
  @:optional final oncanplaythrough:HtmlAttribute<EventListener>;
  @:optional final onchange:HtmlAttribute<EventListener>;
  @:optional final onclick:HtmlAttribute<EventListener>;
  @:optional final oncontextmenu:HtmlAttribute<EventListener>;
  @:optional final ondblclick:HtmlAttribute<EventListener>;
  @:optional final ondrag:HtmlAttribute<EventListener>;
  @:optional final ondragend:HtmlAttribute<EventListener>;
  @:optional final ondragenter:HtmlAttribute<EventListener>;
  @:optional final ondragleave:HtmlAttribute<EventListener>;
  @:optional final ondragover:HtmlAttribute<EventListener>;
  @:optional final ondragstart:HtmlAttribute<EventListener>;
  @:optional final ondrop:HtmlAttribute<EventListener>;
  @:optional final ondurationchange:HtmlAttribute<EventListener>;
  @:optional final onemptied:HtmlAttribute<EventListener>;
  @:optional final onended:HtmlAttribute<EventListener>;
  @:optional final oninput:HtmlAttribute<EventListener>;
  @:optional final oninvalid:HtmlAttribute<EventListener>;
  @:optional final oncompositionstart:HtmlAttribute<EventListener>;
  @:optional final oncompositionupdate:HtmlAttribute<EventListener>;
  @:optional final oncompositionend:HtmlAttribute<EventListener>;
  @:optional final onkeydown:HtmlAttribute<EventListener>;
  @:optional final onkeypress:HtmlAttribute<EventListener>;
  @:optional final onkeyup:HtmlAttribute<EventListener>;
  @:optional final onload:HtmlAttribute<EventListener>;
  @:optional final onloadeddata:HtmlAttribute<EventListener>;
  @:optional final onloadedmetadata:HtmlAttribute<EventListener>;
  @:optional final onloadstart:HtmlAttribute<EventListener>;
  @:optional final onmousedown:HtmlAttribute<EventListener>;
  @:optional final onmouseenter:HtmlAttribute<EventListener>;
  @:optional final onmouseleave:HtmlAttribute<EventListener>;
  @:optional final onmousemove:HtmlAttribute<EventListener>;
  @:optional final onmouseout:HtmlAttribute<EventListener>;
  @:optional final onmouseover:HtmlAttribute<EventListener>;
  @:optional final onmouseup:HtmlAttribute<EventListener>;
  @:optional final onpause:HtmlAttribute<EventListener>;
  @:optional final onplay:HtmlAttribute<EventListener>;
  @:optional final onplaying:HtmlAttribute<EventListener>;
  @:optional final onprogress:HtmlAttribute<EventListener>;
  @:optional final onratechange:HtmlAttribute<EventListener>;
  @:optional final onreset:HtmlAttribute<EventListener>;
  @:optional final onresize:HtmlAttribute<EventListener>;
  @:optional final onscroll:HtmlAttribute<EventListener>;
  @:optional final onseeked:HtmlAttribute<EventListener>;
  @:optional final onseeking:HtmlAttribute<EventListener>;
  @:optional final onselect:HtmlAttribute<EventListener>;
  @:optional final onshow:HtmlAttribute<EventListener>;
  @:optional final onstalled:HtmlAttribute<EventListener>;
  @:optional final onsubmit:HtmlAttribute<EventListener>;
  @:optional final onsuspend:HtmlAttribute<EventListener>;
  @:optional final ontimeupdate:HtmlAttribute<EventListener>;
  @:optional final onvolumechange:HtmlAttribute<EventListener>;
  @:optional final onwaiting:HtmlAttribute<EventListener>;
  @:optional final onpointercancel:HtmlAttribute<EventListener>;
  @:optional final onpointerdown:HtmlAttribute<EventListener>;
  @:optional final onpointerup:HtmlAttribute<EventListener>;
  @:optional final onpointermove:HtmlAttribute<EventListener>;
  @:optional final onpointerout:HtmlAttribute<EventListener>;
  @:optional final onpointerover:HtmlAttribute<EventListener>;
  @:optional final onpointerenter:HtmlAttribute<EventListener>;
  @:optional final onpointerleave:HtmlAttribute<EventListener>;
  @:optional final ongotpointercapture:HtmlAttribute<EventListener>;
  @:optional final onlostpointercapture:HtmlAttribute<EventListener>;
  @:optional final onfullscreenchange:HtmlAttribute<EventListener>;
  @:optional final onfullscreenerror:HtmlAttribute<EventListener>;
  @:optional final onpointerlockchange:HtmlAttribute<EventListener>;
  @:optional final onpointerlockerror:HtmlAttribute<EventListener>;
  @:optional final onerror:HtmlAttribute<EventListener>;
  @:optional final ontouchstart:HtmlAttribute<EventListener>;
  @:optional final ontouchend:HtmlAttribute<EventListener>;
  @:optional final ontouchmove:HtmlAttribute<EventListener>;
  @:optional final ontouchcancel:HtmlAttribute<EventListener>;
}
